=== RockefellerArchiveCenter/ATReference/conf/lookupListValues.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
 <xs:element name="atLookupLists">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="list"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="usage"/>
        <xs:choice>
          <xs:element maxOccurs="unbounded" ref="pair"/>
          <xs:element maxOccurs="unbounded" ref="value"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="listType" use="required" type="xs:integer"/>
      <xs:attribute name="name" use="required"/>
		<xs:attribute name="pairedValues" type="xs:boolean"/>
        <xs:attribute name="restrictToNmtoken" type="xs:boolean"/>
        <xs:attribute name="allowOtherOption" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="usage">
    <xs:complexType>
      <xs:attribute name="className" use="required"/>
      <xs:attribute name="field" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pair">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value"/>
        <xs:element ref="code"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="code" type="xs:string"/>
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:attribute name="editable" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RockefellerArchiveCenter/ATReference/conf/lookupListValues.xml
<?xml version="1.0" encoding="UTF-8"?>
<atLookupLists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://archiviststoolkit.org/toolkit/ATspecification/lookupListValues.xsd">

<!-- Reviewed and revised by AT Team (BDW lead) on 8 Nov. 2007. -->

	<!--Type 1 List: The list may be edited by adding modifying, merging, or deleting values.   -->
	
	<list name="Acquisition type" listType="1">
		
		<usage className="org.archiviststoolkit.model.Accessions" field="acquisitionType"/>
		
		<value>Deposit</value>
		
		<value>Gift</value>
		
		<value>Purchase</value>
		
		<value>Transfer</value>
		
	</list>		
	
	<list listType="1" name="Calendar" restrictToNmtoken="true">
		
		<value>gregorian</value>
		
	</list>
	
	<list name="Container types" listType="1" restrictToNmtoken="true">
		
		<usage className="org.archiviststoolkit.model.ArchDescriptionAnalogInstances"
			field="container1Type"/>
		
		<usage className="org.archiviststoolkit.model.ArchDescriptionAnalogInstances"
			field="container2Type"/>
		
		<usage className="org.archiviststoolkit.model.ArchDescriptionAnalogInstances"
			field="container3Type"/>
		
		<value>Bin</value>
		
		<value>Box</value>
		
		<value>Box-folder</value>
		
		<value>Carton</value>
		
		<value>Cassette</value>
		
		<value>Disk</value>
		
		<value>Drawer</value>
		
		<value>Folder</value>
		
		<value>Frame</value>
		
		<value>Map-case</value>
		
		<value>Object</value>
		
		<value>Oversize</value>
		
		<value>Page</value>
		
		<value>Reel</value>
		
		<value>Reel-Frame</value>
		
		<value>Volume</value>
		
	</list>
	
	<list name="Description rules" listType="1" pairedValues="true">
		
		<!-- Default  values drawn from the MARC code list for Description Conventions: http://www.loc.gov/marc/relators/reladesc.html  . -->
		
		<usage className="org.archiviststoolkit.model.Resources" field="descriptionRules"/>
		
		<pair>
			
			<value>Anglo-American Cataloguing Rules</value>
			
			<code>aacr</code>
			
		</pair>
		
		<pair>
			
			<value>Cataloging Cultural Objects</value>
			
			<code>cco</code>
			
		</pair>
		
		<pair>
			
			<value>Describing Archives: A Content Standard</value>
			
			<code>dacs</code>
			
		</pair>
		
		<pair>
			
			<value>Rules for Archival Description</value>
			
			<code>rad</code>
			
		</pair>
		
	</list>
		
	<list listType="1" name="Era" restrictToNmtoken="true">
		
		<value>ce</value>
		
	</list>
	
	<list name="Extent type" listType="1">
		
		<usage className="org.archiviststoolkit.model.Accessions" field="extentType"/>
		
		<usage className="org.archiviststoolkit.model.Resources" field="extentType"/>
		
		<usage className="org.archiviststoolkit.model.ResourcesComponents" field="extentType"/>
		
		<usage className="org.archiviststoolkit.model.Deaccessions" field="extentType"/>
		
		<value>Cubic feet</value>
		
		<value>Linear feet</value>
		
	</list>
	
	<list name="File use attributes" listType="1">
	
	<!-- Default  values drawn from the UC, San Diego Libraries list of File Use Types. -->
		
		<usage className="org.archiviststoolkit.model.FileVersions" field="useStatement"/>
		
		<value>Audio-Clip</value>
			
		<value>Audio-Master</value>
		
		<value>Audio-Master-Edited</value>
		
		<value>Audio-Service</value>
		
		<value>Audio-Streaming</value>
		
		<value>Image-Master</value>
		
		<value>Image-Master-Edited</value>
		
		<value>Image-Service</value>
		
		<value>Image-Service-HighRes</value>
		
		<value>Image-Service-MedRes</value>
		
		<value>Image-Service-LowRes</value>
		
		<value>Image-Service-Edited</value>
		
		<value>Image-Thumbnail</value>
		
		<value>Text-Codebook</value>
		
		<value>Text-Data</value>
		
		<value>Text-Data Definition</value>
				
		<value>Text-Georeference</value>
		
		<value>Text-Master</value>
		
		<value>Text-OCR-Edited</value>
		
		<value>Text-OCR-Unedited</value>
		
		<value>Text-Service</value>

		<value>Text-TEI-Transcripted</value>
		
		<value>Text-TEI-Translated</value>
			
		<value>Video-Clip</value>
				
		<value>Video-Master</value>
		
		<value>Video-Master-Edited</value>
		
		<value>Video-Service</value>
		
		<value>Video-Streaming</value>
	
		
	</list>
	
	<list name="Finding aid status" listType="1" restrictToNmtoken="true">
		
		<usage className="org.archiviststoolkit.model.Resources" field="findingAidStatus"/>
		
		<value>Completed</value>
		<value>In_process</value>
		<value>Under_revision</value>
		<value>Unprocessed</value>
		
	</list>
	
	<list name="Name description type" listType="1">
		
		<usage className="org.archiviststoolkit.model.Names" field="descriptionType"/>
		
		<value>Administrative History</value>
		
		<value>Biography</value>
		
	</list>
	
	<list name="Name link form" listType="1">
		
        <usage className="org.archiviststoolkit.model.ArchDescriptionNames" field="form"/>
        
        <!-- begin RAC patron module addition -->
        <usage className="org.rac.model.PatronPublicationsNames" field="form"/>
        <usage className="org.rac.model.PatronVisitsNames" field="form"/>
        <!-- end RAC patron module addition -->

		<value>Administration</value>
		
		<value>Archives</value>
		
		<value>Correspondence</value>
		
		<value>Diaries</value>
		
		<value>History</value>
		
		<value>History-Sources</value>
		
		<value>Pictorial works</value>
		
		<value>Trials, litigation, etc.</value>
		
	</list>
	
	<list name="Name source" listType="1" pairedValues="true">
		
		<!-- Terms derived from MARC code list for Term, Name, Title Sources: http://www.loc.gov/marc/relators/relasour.html -->
		
		<usage className="org.archiviststoolkit.model.Names" field="nameSource"/>
		
		<pair>
			
			<value>Local Sources</value>
			
			<code>local</code>
			
		</pair>
		
		<pair>
			
			<value>NACO Authority File</value>
			
			<code>naf</code>
			
		</pair>
		
		<pair>
			
			<value>NAD/ARK II Authority Database</value>
			
			<code>nad</code>
			
		</pair>
		
		<pair>
			
			<value>Union List of Artist Names</value>
			
			<code>ulan</code>
			
		</pair>
		
	</list>
	
	<list name="Name rules" listType="1" pairedValues="true">
		
		<!-- Terms drawn from MARC Code List for Description Conventions: http://www.loc.gov/marc/relators/reladesc.html  -->
		
		<usage className="org.archiviststoolkit.model.Names" field="nameRule"/>
		
		<pair>
			
			<value>Anglo-American Cataloguing Rules</value>
			
			<code>aacr</code>
			
		</pair>
		
		<pair>
			
			<value>Describing Archives: A Content Standard</value>
			
			<code>dacs</code>
			
		</pair>
		
		<pair>
			
			<value>Local</value>
			
			<code>local</code>
			
		</pair>
		
	</list>
	
	<list name="Processing Priorities" listType="1">
		
		<usage className="org.archiviststoolkit.model.Accessions" field="processingPriority"/>
		
		<value>High</value>
		
		<value>Medium</value>
		
		<value>Low</value>
		
	</list>
	
	<list name="Processing Statuses" listType="1">
		
		<usage className="org.archiviststoolkit.model.Accessions" field="processingStatus"/>
		
		<value>New</value>
		
		<value>In Progress</value>
		
		<value>Processed</value>
		
	</list>
	
	<list name="Repository Note Types" listType="1">
		
		<usage className="org.archiviststoolkit.model.RepositoryNotes" field="label"/>
		
		<value>Access Policy</value>
		
		<value>Collection Policy</value>
		
		<value>Hours of Operation</value>
		
		<value>Repository History</value>
		
		<value>Repository Description</value>
	
	</list>
	
	<list name="Resource type" listType="1">
		
		<usage className="org.archiviststoolkit.model.Accessions" field="resourceType"/>
		
		<value>Collection</value>
		
		<value>Papers</value>
		
		<value>Records</value>
		
	</list>
	
	<list name="Subject term source" listType="1" pairedValues="true">
		
		<!-- Terms derived from MARC code list for Term, Name, Title Sources: http://www.loc.gov/marc/relators/relasour.html -->
		
		<usage className="org.archiviststoolkit.model.Subjects" field="subjectSource"/>
		
		<pair>
			
			<value>Art &amp; Architecture Thesaurus</value>
			
			<code>aat</code>
			
		</pair>
		
		<pair>
			
			<value>Dictionary of Occupational Titles</value>
			
			<code>dot</code>
			
		</pair>
		
		<pair>
			
			<value>Genre Terms: A Thesaurus for Use in Rare Book and Special Collections Cataloging</value>
			
			<code>rbgenr</code>
			
		</pair>
		
		<pair>
			
			<value>GeoRef Thesaurus</value>
			
			<code>georeft</code>
			
		</pair>
		
		<pair>
			
			<value>Getty Thesaurus of Geographic Names</value>
			
			<code>tgn</code>
			
		</pair>
		
		<pair>
			
			<value>Library of Congress Subject Headings</value>
			
			<code>lcsh</code>
			
		</pair>
		
		<pair>
			
			<value>Local sources</value>
			
			<code>local</code>
			
		</pair>
		
		<pair>
			
			<value>Medical Subject Headings</value>
			
			<code>mesh</code>
			
		</pair>
		
		<pair>
			
			<value>Thesaurus for Graphic Materials</value>
			
			<code>gmgpc</code>
			
		</pair>
		
	</list>

	<!-- Type 2 List:  The list may not be edited either by adding values, merging values, modifying values, or deleting values. -->

	<list name="Actuate" listType="2">
		
		<!-- Drawn from the values provided for the "actuate" attribute in the list of linking  attributes in the EAD TAG Library: http://www.loc.gov/ead/tglib/att_link.html.  -->
		
		<usage className="org.archiviststoolkit.model.ExternalReference" field="actuate"/>
		
		<usage className="org.archiviststoolkit.model.FileVersions" field="eadDaoActuate"/>
		
		<usage className="org.archiviststoolkit.model.DigitalObjects" field="eadDaoActuate"/>
		
		<value>none</value>
		
		<value>other</value>
		
		<value>onLoad</value>
		
		<value>onRequest</value>
		
	</list>
	
	<list name="Digital object types" listType="2">
		
		<!-- Drawn from the MODS value set for the <typeOfResource> element: http://www.loc.gov/standards/mods/v3/mods-3-3-outline-review-new.html#typeOfResource. -->
		
		<usage className="org.archiviststoolkit.model.DigitalObjects" field="objectType"/>
		
		<value>cartographic</value>
		
		<value>mixed material</value>
